const realImageFiles = [
    "1st_birthday_balloon_set_for_boys.jpeg",
    "Foil_Fringe_Curtain.jpeg",
    "H_B_D_balloon_set.jpeg",
    "acrylic_annyiversary_cake_topper.jpeg",
    "acrylic_birthday_cake_topper.jpeg",
    "acrylic_bride_to_be_topper.jpeg",
    "acrylic_cake_topper.jpeg",
    "acrylic_cake_topper_in_english.jpeg",
    "acrylic_date_fix_topper.jpeg",
    "acrylic_new_year_cake_topper.jpeg",
    "air_pump.jpeg",
    "anniversary_v.jpeg",
    "baat_pakki_and_engagement_banner.jpeg",
    "balloon_packets.jpeg",
    "balloons_packet.jpeg",
    "barbie_birthday_set.jpeg",
    "bear_birthday_set.jpeg",
    "big_balloon.jpeg",
    "birthday_banners.jpeg",
    "birthday_boy_v.jpeg",
    "birthday_candle.jpeg",
    "birthday_candles.jpeg",
    "birthday_cap.jpeg",
    "birthday_eye_mask.jpeg",
    "birthday_girl_or_boy_balloon_set.jpeg",
    "birthday_set_premium.jpeg",
    "blue_birthday_balloon_set.jpeg",
    "bride_to_be_balloon_set.jpeg",
    "bride_to_be_banner.jpeg",
    "bride_to_be_foil_balloons.jpeg",
    "bride_to_be_hairband.jpeg",
    "candle_light.jpeg",
    "color_smoke.jpeg",
    "colorful_balloons_with_transparent_balloons.jpeg",
    "colorful_candles.jpeg",
    "date_fix_banner.jpeg",
    "date_fix_foil_balloon.jpeg",
    "dispossible_birthday_plate.jpeg",
    "dispossible_printed_Plates.jpeg",
    "doted_balloons.jpeg",
    "eid_mubarak_envelope.jpeg",
    "engagement_foil_balloons.jpeg",
    "fairy_lights.jpeg",
    "fancy_Knife.jpeg",
    "fancy_birthday_set.jpeg",
    "fancy_eye_cat_mask.jpeg",
    "foil_balloons.jpeg",
    "gift_basket.jpeg",
    "gift_wrapping_ribbon_in_golden_and_white.jpeg",
    "girl_or_boy_foil_balloon.jpeg",
    "glittery_bride_to_be.jpeg",
    "gold_silver_birthday_boy_and_birthday_girl_topper.jpeg",
    "golden_birthday_candle.jpeg",
    "golden_bride_to_be_hairband.jpeg",
    "golden_crown.jpeg",
    "happy_birthday_balloon_set.jpeg",
    "happy_birthday_balloons.jpeg",
    "happy_birthday_banner.jpeg",
    "happy_bithday_banner_silver.jpeg",
    "it's_a_boy_foil_balloon_set.jpeg",
    "it's_a_gir_balloon_set.jpeg",
    "it's_a_girl_balloon_set.jpeg",
    "it's_a_girl_foil_balloon_set.jpeg",
    "it's_boy_foil_balloon.jpeg",
    "love_printed_mug.jpeg",
    "love_teddy_bear.jpeg",
    "luxury_balloon_set.jpeg",
    "mom_to_be_v.jpeg",
    "musical_barbie_doll.jpeg",
    "musical_birthday_candle.jpeg",
    "musical_doll.jpeg",
    "party_popper.jpeg",
    "pink_love_teddy_bear.jpeg",
    "plastic_ribbon.jpeg",
    "red_and_black_balloon_set.jpeg",
    "red_happy_birthday_banner.jpeg",
    "silver_bride_to_be_hairband.jpeg",
    "simple_candles_with_sparkle_ones.jpeg",
    "snow_spray.jpeg",
    "sparkle_candles.jpeg",
    "spiderman_balloon_set.jpeg",
    "straight_colorful_candles.jpeg",
    "ummrah_mubarak_balloon_set_golden.jpeg",
    "ummrah_mubarak_banner.jpeg",
    "unicorn_birthday_set.jpeg",
    "wavy_birthday_candles.jpeg",
    "welcome_baba_banner.jpeg",
    "welcome_baby_banner.jpeg",
    "welcome_baby_foil_balloon.jpeg",
    "welcome_baby_foil_balloon_set.jpeg",
    "welcome_balloon_banner.jpeg",
    "welcome_banner.jpeg"
];

function formatName(filename) {
    if(filename.includes("WhatsApp")) return "Premium Gift Item";
    return filename.replace('.jpeg','').replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
}

const customPrices = {
    "snow_spray.jpeg": 250,
    "fairy_lights.jpeg": 200,
    "love_printed_mug.jpeg": 350,
    "straight_colorful_candles.jpeg": 230,
    "musical_doll.jpeg": 850,
    "musical_barbie_doll.jpeg": 850,
    "love_teddy_bear.jpeg": 1350,
    "pink_love_teddy_bear.jpeg": 850,
    "bride_to_be_hairband.jpeg": 300,
    "candle_light.jpeg": 300,
    "fancy_eye_cat_mask.jpeg": 200,
    "fancy_Knife.jpeg": 100,
    "musical_birthday_candle.jpeg": 450,
    "sparkle_candles.jpeg": 230,
    "wavy_birthday_candles.jpeg": 250,
    "dispossible_birthday_plate.jpeg": 230,
    "dispossible_printed_Plates.jpeg": 250,
    "unicorn_birthday_set.jpeg": 1750,
    "birthday_cap.jpeg": 120,
    "birthday_candle.jpeg": 130,
    "silver_bride_to_be_hairband.jpeg": 300,
    "plastic_ribbon.jpeg": 150,
    "baat_pakki_and_engagement_banner.jpeg": 350,
    "welcome_baby_banner.jpeg": 350,
    "1st_birthday_balloon_set_for_boys.jpeg": 450,
    "spiderman_balloon_set.jpeg": 450,
    "red_happy_birthday_banner.jpeg": 350,
    "date_fix_banner.jpeg": 350,
    "luxury_balloon_set.jpeg": 1700,
    "happy_birthday_banner.jpeg": 350,
    "happy_bithday_banner_silver.jpeg": 350,
    "it's_boy_foil_balloon.jpeg": 400,
    "it's_a_boy_foil_balloon_set.jpeg": 350,
    "acrylic_cake_topper_in_english.jpeg": 250,
    "Foil_Fringe_Curtain.jpeg": 200,
    "H_B_D_balloon_set.jpeg": 350,
    "acrylic_annyiversary_cake_topper.jpeg": 230,
    "acrylic_birthday_cake_topper.jpeg": 350,
    "acrylic_new_year_cake_topper.jpeg": 220,
    "acrylic_cake_topper.jpeg": 300,
    "acrylic_date_fix_topper.jpeg": 230,
    "gold_silver_birthday_boy_and_birthday_girl_topper.jpeg": 350,
    "golden_birthday_candle.jpeg": 200,
    "golden_crown.jpeg": 400,
    "happy_birthday_balloon_set.jpeg": 350,
    "golden_bride_to_be_hairband.jpeg": 300,
    "happy_birthday_balloons.jpeg": 150,
    "it's_a_girl_balloon_set.jpeg": 450,
    "it's_a_girl_foil_balloon_set.jpeg": 450,
    "colorful_balloons_with_transparent_balloons.jpeg": 250,
    "colorful_candles.jpeg": 250,
    "date_fix_foil_balloon.jpeg": 400,
    "anniversary_v.jpeg": 230,
    "balloon_packets.jpeg": 280,
    "balloons_packet.jpeg": 700,
    "barbie_birthday_set.jpeg": 1750,
    "big_balloon.jpeg": 300,
    "fancy_birthday_set.jpeg": 1750,
    "birthday_set_premium.jpeg": 1750,
    "birthday_girl_or_boy_balloon_set.jpeg": 250,
    "birthday_banners.jpeg": 210,
    "birthday_eye_mask.jpeg": 110,
    "blue_birthday_balloon_set.jpeg": 350,
    "birthday_candles.jpeg": 250,
    "bride_to_be_balloon_set.jpeg": 850,
    "bride_to_be_banner.jpeg": 250,
    "bride_to_be_foil_balloons.jpeg": 400,
    "color_smoke.jpeg": 210,
    "engagement_foil_balloons.jpeg": 350,
    "doted_balloons.jpeg": 200,
    "foil_balloons.jpeg": 350,
    "bear_birthday_set.jpeg": 1750,
    "birthday_boy_v.jpeg": 250,
    "gift_wrapping_ribbon_in_golden_and_white.jpeg": 350,
    "girl_or_boy_foil_balloon.jpeg": 300,
    "mom_to_be_v.jpeg": 350,
    "red_and_black_balloon_set.jpeg": 1750,
    "simple_candles_with_sparkle_ones.jpeg": 250,
    "ummrah_mubarak_banner.jpeg": 350,
    "ummrah_mubarak_balloon_set_golden.jpeg": 500,
    "welcome_banner.jpeg": 400,
    "welcome_baby_foil_balloon.jpeg": 500,
    "welcome_baby_foil_balloon_set.jpeg": 1000
};

let newProducts = [];
let idCounter = 1;

realImageFiles.forEach((imgName, i) => {
    let prodName = formatName(imgName);
    let imgSrc = `images/${imgName}`;
    
    // Professional Categorization Logic
    let category = "Decor & Others";
    const lowerName = imgName.toLowerCase();
    
    if (lowerName.includes("balloon")) category = "Balloons";
    else if (lowerName.includes("candle")) category = "Candles";
    else if (lowerName.includes("set")) category = "Birthday Sets";
    else if (lowerName.includes("topper")) category = "Cake Toppers";
    else if (lowerName.includes("mug") || lowerName.includes("teddy") || lowerName.includes("gift")) category = "Gifts";

    const createProd = (name, price) => {
        newProducts.push({
            id: idCounter++,
            name: name,
            basePrice: price,
            category: category,
            imagePlaceholder: `<img src="${imgSrc}" alt="${name}" loading="lazy" onerror="this.outerHTML='${name}<br>(Missing ${imgSrc})'" />`
        });
    };

    if (imgName === "party_popper.jpeg") {
        createProd("Phool Wala Party Popper", 400);
        createProd("Chammak Wala Bara Party Popper", 230);
        createProd("Chammak Wala Chota Party Popper", 200);
    } else if (imgName === "gift_basket.jpeg") {
        createProd("Gift Basket (Large)", 700);
        createProd("Gift Basket (Small)", 400);
    } else {
        let basePriceValue = (i % 5 === 0) ? 200 : (Math.floor(Math.random() * 4800) + 200);
        if (customPrices[imgName]) {
            basePriceValue = customPrices[imgName];
        } else if (imgName.includes("acrylic_annyiversary_cake_topper")) {
            basePriceValue = 1457;
        }
        createProd(prodName, basePriceValue);
    }
});

let products = newProducts;

// Exchange rates block
const exchangeRates = {
    USD: 1, PKR: 278.5, EUR: 0.92, GBP: 0.79, INR: 83.3,
    JPY: 151.7, CNY: 7.23, SAR: 3.75, AED: 3.67, TRY: 32.1,
    AUD: 1.53, CAD: 1.36, SGD: 1.35, MYR: 4.75, IDR: 15900,
    THB: 36.5, PHP: 56.4, KRW: 1350, ZAR: 18.7, BRL: 5.0,
    MXN: 16.5, RUB: 92.5, NGN: 1300, EGP: 47.3, KWD: 0.31,
    QAR: 3.64, OMR: 0.38, BHD: 0.38, JOD: 0.71, ILS: 3.7,
    SEK: 10.7, NOK: 10.8, DKK: 6.8, CHF: 0.9, PLN: 3.9,
    CZK: 23.4, HUF: 360, RON: 4.5, BGN: 1.8, ZMW: 24,
    ZWD: 322, ARS: 860, CLP: 950, COP: 3800, PEN: 3.7,
    VND: 24900, ALL: 95, AMD: 395, AZN: 1.7, BAM: 1.8,
    BGN: 1.8, BDT: 109, HRK: 7, GEL: 2.7, HTG: 132,
    KES: 130, KZT: 446, KGS: 89, LAK: 21000, MGA: 4500,
    MWK: 1700, MAD: 10, MZN: 63, NPR: 133, TWD: 32,
    TZS: 2580, UGX: 3800, UZS: 12600, XAF: 600, XOF: 600,
    BYN: 3.2, ETB: 56, ISK: 140, KHR: 4000, MKD: 57,
    MMK: 2100, MNT: 3400, NZD: 1.6, AFN: 71, IRR: 42000,
    RSD: 108, LKR: 300, SOS: 570, TJS: 10.9, UAH: 39, WST: 2.7
};

const currencySymbols = {
    USD: '$', PKR: 'Rs ', EUR: '€', GBP: '£', INR: '₹', JPY: '¥', CNY: '¥',
    SAR: '﷼', AED: 'د.إ', TRY: '₺', AUD: 'A$', CAD: 'C$', SGD: 'S$',
    MYR: 'RM', IDR: 'Rp', THB: '฿', PHP: '₱', KRW: '₩', ZAR: 'R',
    BRL: 'R$', MXN: '$', RUB: '₽', NGN: '₦', EGP: 'E£', KWD: 'د.ك',
    ILS: '₪', SEK: 'kr', CHF: 'CHF', PLN: 'zł', VND: '₫', BDT: '৳'
};

const languagesList = [
    { code: 'en', name: 'English', currency: 'USD' },
    { code: 'ru', name: 'Roman Urdu', currency: 'PKR' },
    { code: 'ur', name: 'Urdu', currency: 'PKR' },
    { code: 'af', name: 'Afrikaans', currency: 'ZAR' },
    { code: 'sq', name: 'Albanian', currency: 'ALL' },
    { code: 'am', name: 'Amharic', currency: 'ETB' },
    { code: 'ar', name: 'Arabic', currency: 'SAR' },
    { code: 'hy', name: 'Armenian', currency: 'AMD' },
    { code: 'az', name: 'Azerbaijani', currency: 'AZN' },
    { code: 'eu', name: 'Basque', currency: 'EUR' },
    { code: 'be', name: 'Belarusian', currency: 'BYN' },
    { code: 'bn', name: 'Bengali', currency: 'BDT' },
    { code: 'bs', name: 'Bosnian', currency: 'BAM' },
    { code: 'bg', name: 'Bulgarian', currency: 'BGN' },
    { code: 'ca', name: 'Catalan', currency: 'EUR' },
    { code: 'ceb', name: 'Cebuano', currency: 'PHP' },
    { code: 'ny', name: 'Chichewa', currency: 'MWK' },
    { code: 'zh', name: 'Chinese', currency: 'CNY' },
    { code: 'co', name: 'Corsican', currency: 'EUR' },
    { code: 'hr', name: 'Croatian', currency: 'HRK' },
    { code: 'cs', name: 'Czech', currency: 'CZK' },
    { code: 'da', name: 'Danish', currency: 'DKK' },
    { code: 'nl', name: 'Dutch', currency: 'EUR' },
    { code: 'eo', name: 'Esperanto', currency: 'EUR' },
    { code: 'et', name: 'Estonian', currency: 'EUR' },
    { code: 'tl', name: 'Filipino', currency: 'PHP' },
    { code: 'fi', name: 'Finnish', currency: 'EUR' },
    { code: 'fr', name: 'French', currency: 'EUR' },
    { code: 'fy', name: 'Frisian', currency: 'EUR' },
    { code: 'gl', name: 'Galician', currency: 'EUR' },
    { code: 'ka', name: 'Georgian', currency: 'GEL' },
    { code: 'de', name: 'German', currency: 'EUR' },
    { code: 'el', name: 'Greek', currency: 'EUR' },
    { code: 'gu', name: 'Gujarati', currency: 'INR' },
    { code: 'ht', name: 'Haitian Creole', currency: 'HTG' },
    { code: 'ha', name: 'Hausa', currency: 'NGN' },
    { code: 'haw', name: 'Hawaiian', currency: 'USD' },
    { code: 'iw', name: 'Hebrew', currency: 'ILS' },
    { code: 'hi', name: 'Hindi', currency: 'INR' },
    { code: 'hmn', name: 'Hmong', currency: 'CNY' },
    { code: 'hu', name: 'Hungarian', currency: 'HUF' },
    { code: 'is', name: 'Icelandic', currency: 'ISK' },
    { code: 'ig', name: 'Igbo', currency: 'NGN' },
    { code: 'id', name: 'Indonesian', currency: 'IDR' },
    { code: 'ga', name: 'Irish', currency: 'EUR' },
    { code: 'it', name: 'Italian', currency: 'EUR' },
    { code: 'ja', name: 'Japanese', currency: 'JPY' },
    { code: 'jw', name: 'Javanese', currency: 'IDR' },
    { code: 'kn', name: 'Kannada', currency: 'INR' },
    { code: 'kk', name: 'Kazakh', currency: 'KZT' },
    { code: 'km', name: 'Khmer', currency: 'KHR' },
    { code: 'ko', name: 'Korean', currency: 'KRW' },
    { code: 'ku', name: 'Kurdish', currency: 'TRY' },
    { code: 'ky', name: 'Kyrgyz', currency: 'KGS' },
    { code: 'lo', name: 'Lao', currency: 'LAK' },
    { code: 'la', name: 'Latin', currency: 'EUR' },
    { code: 'lv', name: 'Latvian', currency: 'EUR' },
    { code: 'lt', name: 'Lithuanian', currency: 'EUR' },
    { code: 'lb', name: 'Luxembourgish', currency: 'EUR' },
    { code: 'mk', name: 'Macedonian', currency: 'MKD' },
    { code: 'mg', name: 'Malagasy', currency: 'MGA' },
    { code: 'ms', name: 'Malay', currency: 'MYR' },
    { code: 'ml', name: 'Malayalam', currency: 'INR' },
    { code: 'mt', name: 'Maltese', currency: 'EUR' },
    { code: 'mi', name: 'Maori', currency: 'NZD' },
    { code: 'mr', name: 'Marathi', currency: 'INR' },
    { code: 'mn', name: 'Mongolian', currency: 'MNT' },
    { code: 'my', name: 'Myanmar', currency: 'MMK' },
    { code: 'ne', name: 'Nepali', currency: 'NPR' },
    { code: 'no', name: 'Norwegian', currency: 'NOK' },
    { code: 'ps', name: 'Pashto', currency: 'AFN' },
    { code: 'fa', name: 'Persian', currency: 'IRR' },
    { code: 'pl', name: 'Polish', currency: 'PLN' },
    { code: 'pt', name: 'Portuguese', currency: 'EUR' },
    { code: 'pa', name: 'Punjabi', currency: 'INR' },
    { code: 'ro', name: 'Romanian', currency: 'RON' },
    { code: 'st', name: 'Sesotho', currency: 'ZAR' },
    { code: 'sm', name: 'Samoan', currency: 'WST' },
    { code: 'gd', name: 'Scots Gaelic', currency: 'GBP' },
    { code: 'sr', name: 'Serbian', currency: 'RSD' },
    { code: 'sn', name: 'Shona', currency: 'ZWD' },
    { code: 'sd', name: 'Sindhi', currency: 'PKR' },
    { code: 'si', name: 'Sinhala', currency: 'LKR' },
    { code: 'sk', name: 'Slovak', currency: 'EUR' },
    { code: 'sl', name: 'Slovenian', currency: 'EUR' },
    { code: 'so', name: 'Somali', currency: 'SOS' },
    { code: 'es', name: 'Spanish', currency: 'EUR' },
    { code: 'su', name: 'Sundanese', currency: 'IDR' },
    { code: 'sw', name: 'Swahili', currency: 'KES' },
    { code: 'sv', name: 'Swedish', currency: 'SEK' },
    { code: 'tg', name: 'Tajik', currency: 'TJS' },
    { code: 'ta', name: 'Tamil', currency: 'INR' },
    { code: 'te', name: 'Telugu', currency: 'INR' },
    { code: 'th', name: 'Thai', currency: 'THB' },
    { code: 'tr', name: 'Turkish', currency: 'TRY' },
    { code: 'uk', name: 'Ukrainian', currency: 'UAH' },
    { code: 'uz', name: 'Uzbek', currency: 'UZS' },
    { code: 'vi', name: 'Vietnamese', currency: 'VND' },
    { code: 'cy', name: 'Welsh', currency: 'GBP' },
    { code: 'xh', name: 'Xhosa', currency: 'ZAR' },
    { code: 'yi', name: 'Yiddish', currency: 'ILS' },
    { code: 'yo', name: 'Yoruba', currency: 'NGN' },
    { code: 'zu', name: 'Zulu', currency: 'ZAR' }
];
